### ISSUE TITLE
Epoch index for scalars via after_epoch_end not persisted

### ISSUE THREAD

**Issue by sqeph** [louis-she/minetorch#2]
The MNIST example demonstrates how it is possible to add an accuracy metric using the `after_epoch_end` hook. However, the `Trainer` class does not call this hook until after the model has been persisted and so the epoch incrementation for the custom scalar (i.e. `self.state[graph] += 1` in `TensorboardDrawer`) never gets persisted. Because of this, the epoch index of the custom scalar is out of sync, when resuming from a checkpoint.

As a proposed solution, maybe the `after_epoch_end` hook can be invoked before the model is persisted? Or it could be an additional hook...

**Comment by louis-she** [comment]
Thanks for the issue, fixed in https://github.com/louis-she/minetorch/commit/8f3e0e0e790517b97e0e302e0fd9c88c4ba369e5

If you want to make `Minetorch` better, feel free to open PR . I'm considering make `Minetorch` a better [NVIDIA DIGITS](https://developer.nvidia.com/digits), but with modern Python and still for developers.
